// Shell completions and the man page, generated from the live flag
// table (Goal 39). `findbtc -gen-completion=bash|zsh|fish` and
// `findbtc -gen-man` render flag.CommandLine — the same table the
// scanner parses — so a new flag can never miss the completions or
// the man page: the freshness tests regenerate and byte-compare
// against the committed copies under packaging/.
package main

import (
	"flag"
	"fmt"
	"io"
	"sort"
	"strings"
)

// genFlag is one row of the live flag table.
type genFlag struct {
	name   string
	usage  string
	def    string
	isBool bool
}

// boolFlag mirrors flag's internal bool test: bool flags take no
// value, every other flag does.
type boolFlag interface {
	IsBoolFlag() bool
}

// liveFlagTable snapshots the defined flags in sorted order
// (flag.VisitAll already sorts lexicographically).
func liveFlagTable() []genFlag {
	var out []genFlag
	flag.CommandLine.VisitAll(func(f *flag.Flag) {
		_, isBool := f.Value.(boolFlag)
		out = append(out, genFlag{name: f.Name, usage: f.Usage, def: f.DefValue, isBool: isBool})
	})
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

const genHeader = "GENERATED by `findbtc -gen-completion=%s`; do not edit."

// writeCompletion renders a completion script for shell to w.
func writeCompletion(w io.Writer, shell string) error {
	flags := liveFlagTable()
	switch shell {
	case "bash":
		return writeBashCompletion(w, flags)
	case "zsh":
		return writeZshCompletion(w, flags)
	case "fish":
		return writeFishCompletion(w, flags)
	default:
		return fmt.Errorf("unknown shell %q (want bash, zsh, or fish)", shell)
	}
}

func writeBashCompletion(w io.Writer, flags []genFlag) error {
	var names []string
	for _, f := range flags {
		names = append(names, "-"+f.name)
	}
	_, err := fmt.Fprintf(w, `# findbtc bash completion — `+genHeader+`
_findbtc_completions()
{
    local cur="${COMP_WORDS[COMP_CWORD]}"
    case "$cur" in
        -*=*)
            # After -flag=value the value is flag-specific; offer nothing.
            COMPREPLY=()
            ;;
        -*)
            COMPREPLY=( $(compgen -W "%s" -- "$cur") )
            ;;
        *)
            COMPREPLY=( $(compgen -f -- "$cur") )
            ;;
    esac
}
complete -F _findbtc_completions findbtc
`, "bash", strings.Join(names, " "))
	return err
}

// zshEscape quotes a description for single-quoted _arguments use:
// backslash, brackets (spec delimiters), and the quote itself.
func zshEscape(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `[`, `\[`, `]`, `\]`, `'`, `'\''`)
	return r.Replace(s)
}

func writeZshCompletion(w io.Writer, flags []genFlag) error {
	var b strings.Builder
	fmt.Fprintf(&b, "#compdef findbtc\n# findbtc zsh completion — "+genHeader+"\n_arguments -s -S \\\n", "zsh")
	for i, f := range flags {
		end := " \\\n"
		if i == len(flags)-1 {
			end = "\n"
		}
		if f.isBool {
			fmt.Fprintf(&b, "  '-%s[%s]'%s", f.name, zshEscape(f.usage), end)
		} else {
			fmt.Fprintf(&b, "  '-%s[%s]:value:_files'%s", f.name, zshEscape(f.usage), end)
		}
	}
	_, err := io.WriteString(w, b.String())
	return err
}

// fishEscape quotes a description for single-quoted -d use.
func fishEscape(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `'`, `\'`)
	return r.Replace(s)
}

func writeFishCompletion(w io.Writer, flags []genFlag) error {
	var b strings.Builder
	fmt.Fprintf(&b, "# findbtc fish completion — "+genHeader+"\n", "fish")
	for _, f := range flags {
		// -o is fish's old-style single-dash long option, which
		// matches this tool's -flag spelling; -r marks
		// value-taking flags. Positional file completion is
		// fish's default and needs no line.
		if f.isBool {
			fmt.Fprintf(&b, "complete -c findbtc -o %s -d '%s'\n", f.name, fishEscape(f.usage))
		} else {
			fmt.Fprintf(&b, "complete -c findbtc -o %s -r -d '%s'\n", f.name, fishEscape(f.usage))
		}
	}
	_, err := io.WriteString(w, b.String())
	return err
}

// manEscape quotes prose for troff: backslashes double, a leading .
// or ' gets a zero-width guard so it is not read as a request, and
// hyphens render as \- so they never vanish at line breaks.
func manEscape(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, "-", `\-`)
	if strings.HasPrefix(s, ".") || strings.HasPrefix(s, "'") {
		s = `\&` + s
	}
	return s
}

// orphanDocs are the three guides no other doc links to; the man
// page's SEE ALSO points at their installed copies so they stay
// reachable from the package (Goal 39).
var orphanDocs = []string{
	"BENCHMARKS.md",
	"PIPELINE_INGEST.md",
	"RESOURCE_BOUNDS.md",
}

// writeMan renders the findbtc man page (troff) to w. OPTIONS comes
// from the live flag table; the surrounding sections are fixed
// prose kept beside the generator so one source owns the page.
func writeMan(w io.Writer, flags []genFlag) error {
	var b strings.Builder
	b.WriteString(".TH FINDBTC 1\n")
	b.WriteString(".SH NAME\n")
	b.WriteString("findbtc \\- scan raw block devices and forensic images for cryptocurrency wallet traces\n")
	b.WriteString(".SH SYNOPSIS\n")
	b.WriteString("findbtc [options] TARGET [TARGET ...]\n")
	b.WriteString(".br\n.B findbtc\n")
	b.WriteString(".B \\-report\n")
	b.WriteString(".I hits.jsonl\n")
	b.WriteString(".br\n.B findbtc \\-walk\n.I DIR\n")
	b.WriteString(".br\n.B findbtc \\-advise\n.I TARGET\n")
	b.WriteString(".SH DESCRIPTION\n")
	b.WriteString("findbtc scans disks, images, files, and pipes for wallet traces\n")
	b.WriteString("(seed phrases, keys, descriptors, keystores) and, with the secrets\n")
	b.WriteString("profile, leaked credentials. Detections print to stdout; logs,\n")
	b.WriteString("progress, and the final [COMPLETE] line go to stderr, so\n")
	b.WriteString(".B \\-json\n")
	b.WriteString("output stays parseable. The tool is offline by default and never\n")
	b.WriteString("prints key or seed material without the owner\\-only\n")
	b.WriteString(".B \\-\\-reveal\n")
	b.WriteString("flag.\n")
	b.WriteString(".SH OPTIONS\n")
	for _, f := range flags {
		desc := f.usage
		if !f.isBool && f.def != "" {
			desc += fmt.Sprintf(" (default %s)", f.def)
		}
		fmt.Fprintf(&b, ".TP\n.B \\-%s\n%s\n", manEscape(f.name), manEscape(desc))
	}
	b.WriteString(".SH \"EXIT STATUS\"\n")
	b.WriteString(".TP\n.B 0\n")
	b.WriteString("The run covered its target, hits or not. A batch that scanned at\n")
	b.WriteString("least one target exits 0 even when others failed (failures print\n")
	b.WriteString("loudly with a WARNING).\n")
	b.WriteString(".TP\n.B 1\n")
	b.WriteString("Runtime error or zero coverage: nothing was scanned. The reason\n")
	b.WriteString("is on stderr.\n")
	b.WriteString(".TP\n.B 2\n")
	b.WriteString("Bad flags or usage.\n")
	b.WriteString(".TP\n.B 3\n")
	b.WriteString("Hits found, only with\n")
	b.WriteString(".B \\-fail\\-on\\-hit.\n")
	b.WriteString(".SH EXAMPLES\n")
	b.WriteString("Scan a disk to machine\\-readable hits, then triage offline:\n")
	b.WriteString(".PP\n.RS\n.nf\nfindbtc \\-json /dev/sda > hits.jsonl\nfindbtc \\-report hits.jsonl\n.fi\n.RE\n")
	b.WriteString(".PP\nScan several images in one run with per\\-target case\\-log records:\n")
	b.WriteString(".PP\n.RS\n.nf\nfindbtc \\-json \\-case\\-log case.jsonl img1.E01 img2.raw > hits.jsonl\n.fi\n.RE\n")
	b.WriteString(".SH \"SEE ALSO\"\n")
	b.WriteString("The guides below ship in the deb/rpm packages under\n")
	b.WriteString(".I /usr/share/doc/findbtc/\n")
	b.WriteString("and in the repo under\n")
	b.WriteString(".IR docs/ .\n")
	for _, d := range orphanDocs {
		fmt.Fprintf(&b, ".TP\n.I /usr/share/doc/findbtc/%s\n", d)
	}
	b.WriteString(".TP\n.I /usr/share/doc/findbtc/README.md\n")
	b.WriteString(".SH AUTHOR\n")
	b.WriteString("Paul Jones <https://github.com/pauljones0/findbtc>\n")
	_, err := io.WriteString(w, b.String())
	return err
}
