# findbtc bash completion — GENERATED by `findbtc -gen-completion=bash`; do not edit.
_findbtc_completions()
{
    local cur="${COMP_WORDS[COMP_CWORD]}"
    case "$cur" in
        -*=*)
            # After -flag=value the value is flag-specific; offer nothing.
            COMPREPLY=()
            ;;
        -*)
            COMPREPLY=( $(compgen -W "-advise -balance-endpoint -baseline -case-log -checkpoint -complete -complete-max -complete-out -context -dfxml -extract-dir -fail-on-hit -fs -fs-offset -gen-completion -gen-man -hashes -json -patch -profile -report -resume -reveal -s -salvage -salvage-out -targets -tokenlist -tokenlist-max -tokenlist-out -unallocated-only -verify-case-log -version -walk -walk-follow-symlinks -walk-maxdepth -watch -watch-count -watch-format -watch-out" -- "$cur") )
            ;;
        *)
            COMPREPLY=( $(compgen -f -- "$cur") )
            ;;
    esac
}
complete -F _findbtc_completions findbtc
